name: Build

on:
  push:
  pull_request:
  release:

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Install dependencies"
      run: |
       sudo apt update
       sudo apt install libpng-dev libsdl2-dev libsdl2-ttf-dev gettext libtbb-dev libglm-dev libglew-dev libtbb-dev liblua5.3-dev
    - name: "Build"
      run: |
       cmake -DUNIT_TEST=1 -DCMAKE_BUILD_TYPE=Release .
       make -j
    - name: "Run"
      run: |
       ./SymphonyOfEmpiresServer
  
  build-windows:
    strategy:
      matrix:
        config: [Release, Debug]
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: "Install dependencies"
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install cmake
    - name: "Build"
      run: |
        mkdir build
        cmake -S . -B build -DUNIT_TEST=1 -DCMAKE_BUILD_TYPE=${{ matrix.config }} -DCMAKE_TOOLCHAIN_FILE=x64-windows -G "Visual Studio 16 2019"
        cmake --build build --config ${{ matrix.config }}